<?php

namespace ContainerNgb1i9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WWkGuMAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wWkGuMA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wWkGuMA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campaignRepository' => ['privates', 'App\\Repository\\CampaignRepository', 'getCampaignRepositoryService', true],
            'ruleGroupRepository' => ['privates', 'App\\Repository\\RuleGroupRepository', 'getRuleGroupRepositoryService', true],
        ], [
            'campaignRepository' => 'App\\Repository\\CampaignRepository',
            'ruleGroupRepository' => 'App\\Repository\\RuleGroupRepository',
        ]);
    }
}
