<?php

namespace ContainerNgb1i9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P604ylLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P604ylL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P604ylL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chartBuilderInterface' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'leadsRepository' => ['privates', 'App\\Repository\\LeadsRepository', 'getLeadsRepositoryService', true],
        ], [
            'chartBuilderInterface' => '?',
            'entityManagerInterface' => '?',
            'leadsRepository' => 'App\\Repository\\LeadsRepository',
        ]);
    }
}
