<?php

namespace ContainerNgb1i9T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JwUaDCtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JwUaDCt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JwUaDCt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campaignRepository' => ['privates', 'App\\Repository\\CampaignRepository', 'getCampaignRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'leadsRepository' => ['privates', 'App\\Repository\\LeadsRepository', 'getLeadsRepositoryService', true],
            'ruleGroupRepository' => ['privates', 'App\\Repository\\RuleGroupRepository', 'getRuleGroupRepositoryService', true],
        ], [
            'campaignRepository' => 'App\\Repository\\CampaignRepository',
            'entityManagerInterface' => '?',
            'leadsRepository' => 'App\\Repository\\LeadsRepository',
            'ruleGroupRepository' => 'App\\Repository\\RuleGroupRepository',
        ]);
    }
}
