<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ91CKbj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ91CKbj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ91CKbj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ91CKbj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ91CKbj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z91CKbj',
    'container.build_id' => '5a4581b0',
    'container.build_time' => 1657527706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ91CKbj');
