<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgb1i9T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgb1i9T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgb1i9T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgb1i9T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgb1i9T\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ngb1i9T',
    'container.build_id' => 'bae0bee1',
    'container.build_time' => 1657278188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgb1i9T');
