<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/212.27da8a68.js',
                '/build/app.dfafc9fe.js',
            ],
            'css' => [
                '/build/app.6cfb4833.css',
            ],
        ],
    ],
],

]];
